apiVersion: v1
kind: Pod
metadata:
  name: pod-add-settime-capability
spec:
  containers:
    - image:  alpine
      name: main
      command: ["/bin/sleep", "99999"]
      securityContext:
          capabilities:
            add:
              - SYS_TIME