apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-v1
  labels:
    app: kubia
    env: dev
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      name: kubia-v1
      labels:
        app: kubia
        env: dev
    spec:
      containers:
        - image: kasunsjc/kubia:v1
          name:  nodejs

---
apiVersion: v1
kind: Service
metadata:
  name: kubia-rc-svc
  labels:
    app: kubia
    env: dev
spec:
  type: LoadBalancer
  selector:
    app: kubia
  ports:
    - port: 80
      targetPort: 8080
