apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-rc-node
  labels:
    app: kubia-node
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia-node
  template:
    metadata:
      labels:
        app: kubia-node
    spec:
      containers:
        - image:  kasunsjc/kubia
          name:  kubia-node
          ports:
          - name:  http
            containerPort:  8080
            protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi

---

apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30000
  selector:
    app: kubia-node 