apiVersion: v1
kind: ReplicationController 
metadata:
  name: kubia-rc-session
  labels:
    app: front-session
    env: dev
spec:
  replicas: 3
  selector:
    app: front-session
  template:
    metadata:
      name: kubia-rc-session
      labels:
        app: front-session
        env: dev
    spec:
      containers:
        - image:  kasunsjc/kubia
          name:  kubia
          ports:
          - name:  http
            containerPort:  8080
          - name: https
            containerPort: 8443
          - name: mysql
            containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: kubia-session-svc
  labels:
    app: front-svc
    env: dev
spec:
  selector:
    app: front-session
  ports:
    - port: 80
      name: http
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
    - name: mysql
      port: 3306
      targetPort: 3306
  sessionAffinity: ClientIP
  type: ClusterIP