apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-azure
spec:
  resources:
    requests:
      storage: 10Gi
  volumeName: mongo-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: "" 