apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  selector:
    matchLabels:
      app: kubia 
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: kasunraj/kubia:v3
        name: nodejs
