apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-rollingupdate
spec:
  selector:
    matchLabels:
      app: kubia-rollingupdate
  replicas: 10
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: kubia
      labels:
        app: kubia-rollingupdate
    spec:
      containers:
      - image: kasunsjc/kubia:v1
        name: nodejs
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  type: LoadBalancer
  selector:
    app: kubia-rollingupdate
  ports:
  - port: 80
    targetPort: 8080

