apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-rc-lb
  labels:
    app: kubia-lb
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia-lb
  template:
    metadata:
      labels:
        app: kubia-lb
    spec:
      containers:
        - image:  kasunsjc/kubia
          name:  kubia-lb
          ports:
          - name:  http
            containerPort:  8080
            protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi

---

apiVersion: v1
kind: Service
metadata:
  name: kubia-lb
  labels:
    app: kubia
    env: dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: kubia-lb