apiVersion: v1
kind: Pod
metadata:
  name: kubia-hostport
spec:
  containers:
    - image:  kasunsjc/kubia
      name:  kubia
      ports:
      - containerPort: 8000
        hostPort: 9000
        protocol: TCP