apiVersion: v1
kind: Pod
metadata:
  name: pod-with-readonlyfilesystem
spec:
  containers:
    - image:  alpine
      name:  main
      command: ["/bin/sleep", "999999"]
      securityContext:
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: my-volume
          mountPath: /volume
          readOnly: false
  volumes:
    - name: my-volume
      emptyDir:
          {}