apiVersion: v1
kind: Pod
metadata:
  name: pod-run-as-non-root
spec:
  containers:
    - image:  alpine
      name:  main
      command: ["/bin/sleep", "9999999"]
      securityContext:
        runAsNonRoot: true