apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: test-podpolicy
spec:
  hostIPC: false
  hostPID: false
  hostPorts:
    - min: 10000
      max: 11000
    - min: 13000
      max: 14000
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  volumes:
    - '*'