apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: 1.18.1 #<-- Use the word stable for newest version
controlPlaneEndpoint: "master01:6443" #<-- Use the node alias not the IP
networking:
  podSubnet: 192.168.0.0/16