apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
  labels:
    app: kubia-front
    env: dev
spec:
  replicas: 3
  selector:
    app: kubia-front
  template:
    metadata:
      name: kubia-rc
      labels:
        app: kubia-front
        env: dev
    spec:
      containers:
        - image:  kasunsjc/kubia
          name:  kubia
          ports:
          - name:  http
            containerPort:  8080
            protocol: TCP
